POST http://localhost:3000/register
content-type: application/json

{
    "title": "asd",
    "content": "shark@gmail.coma",
    "published": 0
}

###

GET http://localhost:3000/users

###



PUT  http://localhost:3000/update/13
content-type: application/json

{
    "title":"Bago na"
}

###



delete  http://localhost:3000/delete/13
content-type: application/json

